version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  rabbitmq:
    image: rabbitmq:3.12-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
