# Generated by Django 4.2 on 2023-04-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='blog_auth/profile_pics/avatar.webp', upload_to='blog_auth/profile_pics/'),
        ),
    ]
