# Generated by Django 4.2 on 2023-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/post_tbs/thumbnail.png', upload_to='blog/post_tbs/'),
        ),
    ]
